import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'kn' | 'hi';

const translations = {
  en: {
    common: {
      cancel: 'Cancel',
      close: 'Close',
      save: 'Save',
      pending: 'Pending',
      connected: 'Connected',
      connect: 'Connect',
      confirm: 'Confirm',
    },
    dashboard: {
      hello: 'Hello, {{name}}',
      helloThere: 'Hello',
      countdownLabel: 'Countdown',
      totalXp: 'Total XP',
      badges: 'Badges',
      badgesEarned: 'Badges',
      todaysTasks: "Today's Tasks",
      allCompletedTitle: 'All Done!',
      allCompletedSubtitle: 'All daily tasks completed!',
      completedBtn: 'Done',
      tasksCompletedToday: 'Completed Today',
      noTasksCompleted: 'None completed yet.',
      dailyStreak: 'Streak',
      streakDays: '{{count}} Days',
      phases: {
        preop: 'Pre-Op',
        postop: 'Post-Op',
        recovery: 'Recovery',
        setup: 'Setup',
      },
      tasks: {
        medication_logged: 'Log Meds',
        medication_logged_desc: 'Mark daily medicines taken',
        daily_logging: 'Daily Login',
        daily_logging_desc: 'Open app daily for streak',
        wound_photo: 'Upload Photo',
        wound_photo_desc: 'Upload photo to monitor healing',
        symptoms_logging: 'Log Symptoms',
        symptoms_logging_desc: 'Record pain & symptoms',
        autoCompleteHint: 'Auto-completes on logging',
      }
    },
    activity: {
      pageTitle: 'Care Plan',
      canDoTitle: 'Recommended',
      notToDoTitle: 'Avoid',
      canDoSlides: {
        slide1: {
          title: 'High Fiber',
          subtitle: 'Eat vegetables, fruits, grains',
        },
        slide2: {
          title: 'Hydrate Well',
          subtitle: 'Drink plenty of water daily',
        },
        slide3: {
          title: 'Gentle Walk',
          subtitle: 'Keep active with calm walks',
        },
        slide4: {
          title: 'Bed Rest',
          subtitle: 'Get plenty of restful sleep',
        },
        slide5: {
          title: 'Light Chores',
          subtitle: 'Small tasks; no heavy lifting',
        },
      },
      notToDoSlides: {
        slide1: {
          title: 'Junk Food',
          subtitle: 'Avoid fried and heavy meals',
        },
        slide2: {
          title: 'Alcohol',
          subtitle: 'Avoid alcohol during healing',
        },
        slide3: {
          title: 'Running',
          subtitle: 'Avoid running or hard exercise',
        },
        slide4: {
          title: 'Heavy Lifting',
          subtitle: 'Do not lift over 5 lbs',
        },
        slide5: {
          title: 'Bending',
          subtitle: 'Do not bend at the waist',
        },
      },
    },
    diary: {
      pageTitle: 'Diary',
      empty: 'No entries yet. Write below.',
      loadMore: 'Load More',
      addTodayEntry: '+ Add Log',
      placeholder: 'How do you feel today...',
      saveXp: 'Save +15 XP',
      selectMood: 'Select Mood',
      selectMoodAlertTitle: 'Mood',
      selectMoodAlertDesc: 'Please pick a mood.',
      tooShortAlertTitle: 'Too Short',
      tooShortAlertDesc: 'Write at least 10 characters.',
      entryAddedAlertTitle: 'Saved ✅',
      entryAddedAlertDesc: '+15 XP earned!',
      todayHeader: 'Today',
      olderEntriesHeader: 'Older Logs',
      noEntriesToday: 'No logs written today.',
      deleteTitle: 'Delete Entry',
      deleteConfirm: 'Are you sure you want to delete this entry?',
      deleteSuccess: 'Entry deleted successfully.',
      deleteError: 'Could not delete entry. Try again.',
    },
    experts: {
      pageTitle: 'Find Doctors',
      careTeamTitle: 'Care Team',
      emptyDoctors: 'No doctors found.',
      searchPlaceholder: 'Search name or phone...',
      hospitalLocation: 'Hospital Location',
      confirmBooking: 'Confirm Booking',
      bookAppointment: 'Book Appointment',
      specialistSubtitle: 'Hernia Specialist',
      rating: 'Rating',
      reviews: 'reviews',
      consultationFee: 'Fee',
      experience: 'Exp',
      years: 'years',
      location: 'Location',
      aboutDoctor: 'About Doctor',
      removeConnection: 'Remove Connection',
      removeConnectionDesc: 'Remove connection with Dr. {{name}}?',
      removePendingDesc: 'Cancel request to Dr. {{name}}?',
      appointmentBooked: 'Booked! ✅',
      appointmentBookedDesc: 'Appointment scheduled.',
      noDoctorsFound: 'No Doctors Found',
      noDoctorsAvailable: 'No Doctors Available',
      noDoctorsFoundDesc: 'No matches found. Try again.',
      noDoctorsAvailableDesc: 'No new specialists available.',
      viewProfile: 'View Profile →',
      loadingDoctors: 'Loading...',
      connectWithSpecialist: 'Connect with Specialist',
      connectWithSpecialistDesc: 'Share logs & photos for active monitoring.',
      connectWithDoctorBtn: 'Connect',
      requestsPending: 'Pending Requests',
      requestsPendingDesc: 'Awaiting doctor approval.',
      pendingRequestsLabel: 'Pending ({{count}})',
      profileBtn: 'Profile',
      requestSentTitle: 'Sent 📩',
      requestSentDesc: 'Request sent successfully.',
      errorTitle: 'Error',
      sendRequestError: 'Could not send request.',
    },
    reports: {
      pageTitle: 'Wound Health',
      uploadTitle: 'Upload Photo',
      uploadDesc: 'Monitor healing progress',
      sectionHeader: 'Wound Photos',
      deleteTitle: 'Delete Photo',
      deleteConfirm: 'Delete this photo?',
      successUpload: 'Uploaded ✅',
      successUploadDesc: 'Photo uploaded! +30 XP.',
      failUpload: 'Upload Failed',
      failUploadDesc: 'Could not upload. Try again.',
      careTipsHeader: 'Wound Care Tips',
      warningSignsHeader: 'Warning Signs',
      careTips: {
        clean: 'Keep clean & dry',
        cleanSub: 'Protect the incision area',
        clothes: 'Wear loose clothes',
        clothesSub: 'Avoid tight clothing',
        dressing: 'Change dressing daily',
        dressingSub: 'Maintain hygiene',
        scratch: 'Do not scratch',
        scratchSub: 'Prevent wound irritation',
        meds: 'Take meds on time',
        medsSub: 'Support recovery & relief',
        call: 'Call doctor if concerned',
        callSub: 'Reach out for help early',
      },
      warningSigns: {
        redness: 'Redness',
        rednessSub: 'Watch for spreading color',
        swelling: 'Swelling',
        swellingSub: 'Check for abnormal expansion',
        pus: 'Pus Discharge',
        pusSub: 'Report yellow discharge',
        bleeding: 'Bleeding',
        bleedingSub: 'Monitor active blood flow',
      },
    },
    monitor: {
      pageTitle: 'Symptom Report',
      loggedDetails: 'Logged Details',
      severityRating: 'Severity:',
      highSeverity: 'High',
      mediumSeverity: 'Medium',
      mildSeverity: 'Mild',
      loggedSymptoms: 'Symptoms:',
      notes: 'Notes:',
      done: 'Done',
      logTitle: 'Log Symptoms',
      painHeader: 'Pain Level (1-10)',
      symptomsHeader: 'Symptoms',
      painDescriptionHeader: 'Notes (Optional)',
      painPlaceholder: 'Briefly describe pain...',
      submitBtn: 'Submit +20 XP',
      alertTitleHigh: 'High Alert',
      alertMsgHigh: 'Please visit doctor immediately.',
      alertTitleMedium: 'Medium Alert',
      alertMsgMedium: 'Please contact doctor for advice.',
      alertTitleStable: 'Stable',
      alertMsgStable: 'Symptoms stable. Continue monitoring.',
      symptomNames: {
        fever: 'Fever',
        swelling: 'Swelling',
        vomiting: 'Vomiting',
        redness: 'Redness',
        bleeding: 'Bleeding',
        urination: 'Urination issue',
      },
      noSymptomSelected: 'No critical symptoms',
      reportTitle: 'Symptom Report',
      saveError: 'Could not save. Try again.',
      viewHistory: 'View History',
    },
    profile: {
      pageTitle: 'Profile',
      saveDetails: 'Save Details',
      editProfile: 'Edit Profile',
      fullNameLabel: 'Full Name',
      fullNamePlaceholder: 'Enter full name',
      phoneLabel: 'Phone Number',
      phonePlaceholder: 'Your phone number',
      addressLabel: 'Address',
      addressPlaceholder: 'Home address',
      emergencyLabel: 'Emergency Contact',
      emergencyPlaceholder: 'Emergency contact number',
      surgicalPlan: 'Surgical Plan',
      nameRequired: 'Name required',
      nameRequiredDesc: 'Please enter name.',
      invalidDate: 'Invalid date',
      invalidDateDesc: 'Use YYYY-MM-DD format.',
      saved: 'Saved',
      savedDesc: 'Profile updated.',
      saveFailed: 'Save failed',
      saveFailedDesc: 'Could not update. Try again.',
      closePicker: 'Close',
      genderLabel: 'Gender',
      herniaTypeLabel: 'Hernia Type',
      surgeryStatusLabel: 'Surgery Status',
      surgeryTypeLabel: 'Surgery Type',
      surgeryDateLabel: 'Surgery Date',
      surgeryDatePlaceholder: 'Select surgery date',
      logout: 'Logout',
      loggingOut: 'Logging out...',
      defaultName: 'Your name',
      genders: {
        male: 'Male',
        female: 'Female',
        other: 'Other',
      },
      hernias: {
        inguinal: 'Inguinal',
        femoral: 'Femoral',
        umbilical: 'Umbilical',
        incisional: 'Incisional',
      },
      status: {
        notDone: 'Not Done',
        scheduled: 'Scheduled',
        completed: 'Completed',
      },
      types: {
        open: 'Open',
        laparoscopic: 'Laparoscopic',
      },
    },
  },
  kn: {
    common: {
      cancel: 'ರದ್ದು',
      close: 'ಮುಚ್ಚಿ',
      save: 'ಉಳಿಸಿ',
      pending: 'ಬಾಕಿ',
      connected: 'ಸಂಪರ್ಕಿತ',
      connect: 'ಸಂಪರ್ಕಿಸಿ',
      confirm: 'ಖಚಿತಪಡಿಸಿ',
    },
    dashboard: {
      hello: 'ನಮಸ್ಕಾರ, {{name}}',
      helloThere: 'ನಮಸ್ಕಾರ',
      countdownLabel: 'ಕೌಂಟ್‌ಡೌನ್',
      totalXp: 'ಒಟ್ಟು XP',
      badges: 'ಬ್ಯಾಡ್ಜ್',
      badgesEarned: 'ಗಳಿಸಿದ ಬ್ಯಾಡ್ಜ್',
      todaysTasks: 'ಇಂದಿನ ಕೆಲಸಗಳು',
      allCompletedTitle: 'ಎಲ್ಲಾ ಪೂರ್ಣ!',
      allCompletedSubtitle: 'ಇಂದಿನ ಕೆಲಸಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ!',
      completedBtn: 'ಪೂರ್ಣ',
      tasksCompletedToday: 'ಇಂದು ಪೂರ್ಣಗೊಂಡಿವೆ',
      noTasksCompleted: 'ಇನ್ನೂ ಯಾವುದೂ ಇಲ್ಲ.',
      dailyStreak: 'ಸರಣಿ',
      streakDays: '{{count}} ದಿನಗಳು',
      phases: {
        preop: 'ಚಿಕಿತ್ಸೆಗೆ ಮುನ್ನ',
        postop: 'ಚಿಕಿತ್ಸೆಯ ನಂತರ',
        recovery: 'ಚೇತರಿಕೆ',
        setup: 'ಸಿದ್ಧತೆ',
      },
      tasks: {
        medication_logged: 'ಔಷಧಿ ದಾಖಲಿಸಿ',
        medication_logged_desc: 'ದಿನದ ಔಷಧಿಗಳನ್ನು ಗುರುತು ಮಾಡಿ',
        daily_logging: 'ದೈನಂದಿನ ಲಾಗಿನ್',
        daily_logging_desc: 'ಪ್ರತಿದಿನ ಆಪ್ ತೆರೆಯಿರಿ',
        wound_photo: 'ಫೋಟೋ ಹಾಕಿ',
        wound_photo_desc: 'ಗಾಯದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        symptoms_logging: 'ಲಕ್ಷಣ ದಾಖಲಿಸಿ',
        symptoms_logging_desc: 'ನೋವು ಮತ್ತು ಲಕ್ಷಣ ದಾಖಲಿಸಿ',
        autoCompleteHint: 'ದಾಖಲಿಸಿದಾಗ ಪೂರ್ಣಗೊಳ್ಳುತ್ತದೆ',
      }
    },
    activity: {
      pageTitle: 'ಆರೈಕೆ ಯೋಜನೆ',
      canDoTitle: 'ಶಿಫಾರಸು',
      notToDoTitle: 'ತಪ್ಪಿಸಿ',
      canDoSlides: {
        slide1: {
          title: 'ನಾರಿನ ಆಹಾರ',
          subtitle: 'ಹಣ್ಣು, ತರಕಾರಿ, ಧಾನ್ಯ ಸೇವಿಸಿ',
        },
        slide2: {
          title: 'ನೀರು ಕುಡಿಯಿರಿ',
          subtitle: 'ದಿನವಿಡೀ ಸಾಕಷ್ಟು ನೀರು ಕುಡಿಯಿರಿ',
        },
        slide3: {
          title: 'ಸೌಮ್ಯ ನಡಿಗೆ',
          subtitle: 'ಸಣ್ಣ ನಡಿಗೆಯಿಂದ ಸಕ್ರಿಯರಾಗಿರಿ',
        },
        slide4: {
          title: 'ಹಾಸಿಗೆ ವಿಶ್ರಾಂತಿ',
          subtitle: 'ಆರಾಮದಾಯಕ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ',
        },
        slide5: {
          title: 'ಹಗುರ ಕೆಲಸ',
          subtitle: 'ಭಾರ ಎತ್ತದೆ ಸಣ್ಣ ಕೆಲಸ ಮಾಡಿ',
        },
      },
      notToDoSlides: {
        slide1: {
          title: 'ಜಂಕ್ ಫುಡ್',
          subtitle: 'ಕರಿದ ಮತ್ತು ಭಾರಿ ಊಟ ತಪ್ಪಿಸಿ',
        },
        slide2: {
          title: 'ಮದ್ಯಪಾನ',
          subtitle: 'ಚೇತರಿಕೆಗೆ ಮದ್ಯಪಾನ ತಪ್ಪಿಸಿ',
        },
        slide3: {
          title: 'ಓಡುವುದು',
          subtitle: 'ಓಡುವುದು, ಕಠಿಣ ವ್ಯಾಯಾಮ ತಪ್ಪಿಸಿ',
        },
        slide4: {
          title: 'ಭಾರ ಎತ್ತುವುದು',
          subtitle: '೫ ಪೌಂಡ್‌ಗಿಂತ ಹೆಚ್ಚು ಎತ್ತಬೇಡಿ',
        },
        slide5: {
          title: 'ಬಗ್ಗುವುದು',
          subtitle: 'ಸೊಂಟ ಬಗ್ಗಿಸದೆ ಮೊಣಕಾಲು ಬಗ್ಗಿಸಿ',
        },
      },
    },
    diary: {
      pageTitle: 'ದಿನಚರಿ',
      empty: 'ಇನ್ನೂ ಬರೆದಿಲ್ಲ. ಕೆಳಗೆ ಬರೆಯಿರಿ.',
      loadMore: 'ಇನ್ನೂ ಲೋಡ್ ಮಾಡಿ',
      addTodayEntry: '+ ದಿನಚರಿ',
      placeholder: 'ಇಂದು ಹೇಗನಿಸುತ್ತಿದೆ...',
      saveXp: 'ಉಳಿಸಿ +15 XP',
      selectMood: 'ಮನಸ್ಥಿತಿ',
      selectMoodAlertTitle: 'ಮನಸ್ಥಿತಿ',
      selectMoodAlertDesc: 'ದಯವಿಟ್ಟು ಮನಸ್ಥಿತಿ ಆಯ್ಕೆಮಾಡಿ.',
      tooShortAlertTitle: 'ಬಹಳ ಚಿಕ್ಕದು',
      tooShortAlertDesc: 'ಕನಿಷ್ಠ 10 ಅಕ್ಷರ ಬರೆಯಿರಿ.',
      entryAddedAlertTitle: 'ಉಳಿಸಲಾಗಿದೆ ✅',
      entryAddedAlertDesc: '+15 XP ಗಳಿಸಲಾಗಿದೆ!',
      todayHeader: 'ಇಂದು',
      olderEntriesHeader: 'ಹಳೆಯ ದಾಖಲೆಗಳು',
      noEntriesToday: 'ಇಂದು ಯಾವುದೇ ದಾಖಲೆ ಇಲ್ಲ.',
      deleteTitle: 'ದಾಖಲೆ ಅಳಿಸಿ',
      deleteConfirm: 'ಈ ದಾಖಲೆಯನ್ನು ಅಳಿಸಲು ನಿಮಗೆ ಖಚಿತವೇ?',
      deleteSuccess: 'ದಾಖಲೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ.',
      deleteError: 'ಅಳಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ. ಮತ್ತೆ ಯತ್ನಿಸಿ.',
    },
    experts: {
      pageTitle: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
      careTeamTitle: 'ಆರೈಕೆ ತಂಡ',
      emptyDoctors: 'ಯಾರೂ ಕಂಡುಬಂದಿಲ್ಲ.',
      searchPlaceholder: 'ಹೆಸರು, ಫೋನ್‌ನಿಂದ ಹುಡುಕಿ...',
      hospitalLocation: 'ಆಸ್ಪತ್ರೆಯ ಸ್ಥಳ',
      confirmBooking: 'ಬುಕ್ಕಿಂಗ್ ಖಚಿತಪಡಿಸಿ',
      bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
      specialistSubtitle: 'ಹರ್ನಿಯಾ ತಜ್ಞರು',
      rating: 'ರೇಟಿಂಗ್',
      reviews: 'ವಿಮರ್ಶೆ',
      consultationFee: 'ಶುಲ್ಕ',
      experience: 'ಅನುಭವ',
      years: 'ವರ್ಷ',
      location: 'ಸ್ಥಳ',
      aboutDoctor: 'ವೈದ್ಯರ ಬಗ್ಗೆ',
      removeConnection: 'ಸಂಪರ್ಕ ಕಡಿತ',
      removeConnectionDesc: 'ಸಂಪರ್ಕ ಕಡಿತಗೊಳಿಸಬೇಕೆ?',
      removePendingDesc: 'ವಿನಂತಿ ರದ್ದುಗೊಳಿಸಬೇಕೆ?',
      appointmentBooked: 'ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ! ✅',
      appointmentBookedDesc: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ನಿಗದಿಯಾಗಿದೆ.',
      noDoctorsFound: 'ವೈದ್ಯರು ಸಿಕ್ಕಿಲ್ಲ',
      noDoctorsAvailable: 'ವೈದ್ಯರು ಲಭ್ಯವಿಲ್ಲ',
      noDoctorsFoundDesc: 'ಹೊಂದಿಕೆಯಾಗುವ ವೈದ್ಯರು ಇಲ್ಲ.',
      noDoctorsAvailableDesc: 'ಹೊಸ ವೈದ್ಯರು ಲಭ್ಯವಿಲ್ಲ.',
      viewProfile: 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ →',
      loadingDoctors: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      connectWithSpecialist: 'ತಜ್ಞರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
      connectWithSpecialistDesc: 'ಡೇಟಾ ಮತ್ತು ಫೋಟೋಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.',
      connectWithDoctorBtn: 'ಸಂಪರ್ಕಿಸಿ',
      requestsPending: 'ಬಾಕಿ ವಿನಂತಿಗಳು',
      requestsPendingDesc: 'ವೈದ್ಯರ ಒಪ್ಪಿಗೆಗೆ ಕಾಯಲಾಗುತ್ತಿದೆ.',
      pendingRequestsLabel: 'ಬಾಕಿ ({{count}})',
      profileBtn: 'ಪ್ರೊಫೈಲ್',
      requestSentTitle: 'ಕಳುಹಿಸಲಾಗಿದೆ 📩',
      requestSentDesc: 'ವಿನಂತಿ ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.',
      errorTitle: 'ದೋಷ',
      sendRequestError: 'ವಿನಂತಿ ಕಳುಹಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ.',
    },
    reports: {
      pageTitle: 'ಗಾಯದ ಆರೋಗ್ಯ',
      uploadTitle: 'ಫೋಟೋ ಹಾಕಿ',
      uploadDesc: 'ವಾಸಿಯಾಗುವ ಪ್ರಕ್ರಿಯೆ ನೋಡಿ',
      sectionHeader: 'ಗಾಯದ ಫೋಟೋಗಳು',
      deleteTitle: 'ಫೋಟೋ ಅಳಿಸಿ',
      deleteConfirm: 'ಫೋಟೋ ಅಳಿಸಬೇಕೇ?',
      successUpload: 'ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ ✅',
      successUploadDesc: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ! +30 XP.',
      failUpload: 'ಅಪ್‌ಲೋಡ್ ವಿಫಲ',
      failUploadDesc: 'ಅಪ್‌ಲೋಡ್ ಆಗಿಲ್ಲ. ಮತ್ತೆ ಯತ್ನಿಸಿ.',
      careTipsHeader: 'ಗಾಯದ ಆರೈಕೆ ಸಲಹೆಗಳು',
      warningSignsHeader: 'ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳು',
      careTips: {
        clean: 'ಶುಷ್ಕ ಹಾಗೂ ಸ್ವಚ್ಛವಾಗಿಡಿ',
        cleanSub: 'ಗಾಯದ ಭಾಗವನ್ನು ರಕ್ಷಿಸಿ',
        clothes: 'ಸಡಿಲ ಬಟ್ಟೆ ಧರಿಸಿ',
        clothesSub: 'ಬಿಗಿಯಾದ ಬಟ್ಟೆ ತಪ್ಪಿಸಿ',
        dressing: 'ದಿನವೂ ಬ್ಯಾಂಡೇಜ್ ಬದಲಿಸಿ',
        dressingSub: 'ನೈರ್ಮಲ್ಯ ಕಾಪಾಡಿ',
        scratch: 'ಗಾಯ ಕೆರೆಯಬೇಡಿ',
        scratchSub: 'ಕಿರಿಕಿರಿ ತಡೆಯಿರಿ',
        meds: 'ಸಮಯಕ್ಕೆ ಔಷಧಿ ಸೇವಿಸಿ',
        medsSub: 'ನೋವು ನಿವಾರಣೆ ಮತ್ತು ಚೇತರಿಕೆ',
        call: 'ಸಮಸ್ಯೆಯಿದ್ದರೆ ಕರೆ ಮಾಡಿ',
        callSub: 'ಬೇಗನೆ ಸಹಾಯ ಪಡೆಯಿರಿ',
      },
      warningSigns: {
        redness: 'ಕೆಂಪಾಗುವುದು',
        rednessSub: 'ಹರಡುವ ಕೆಂಪು ಬಣ್ಣ ಗಮನಿಸಿ',
        swelling: 'ಊತ',
        swellingSub: 'ಅಸಹಜ ಊತ ಪರಿಶೀಲಿಸಿ',
        pus: 'ಕೀವು ಬರುವುದು',
        pusSub: 'ಹಳದಿ ದ್ರವ ವರದಿ ಮಾಡಿ',
        bleeding: 'ರಕ್ತಸ್ರಾವ',
        bleedingSub: 'ರಕ್ತದ ಹರಿವು ಗಮನಿಸಿ',
      },
    },
    monitor: {
      pageTitle: 'ಲಕ್ಷಣಗಳ ವರದಿ',
      loggedDetails: 'ದಾಖಲಾದ ವಿವರಗಳು',
      severityRating: 'ತೀವ್ರತೆ:',
      highSeverity: 'ಹೆಚ್ಚು',
      mediumSeverity: 'ಮಧ್ಯಮ',
      mildSeverity: 'ಕಡಿಮೆ',
      loggedSymptoms: 'ಲಕ್ಷಣಗಳು:',
      notes: 'ಟಿಪ್ಪಣಿ:',
      done: 'ಮುಗಿದಿದೆ',
      logTitle: 'ಲಕ್ಷಣ ದಾಖಲಿಸಿ',
      painHeader: 'ನೋವಿನ ಮಟ್ಟ (1-10)',
      symptomsHeader: 'ಲಕ್ಷಣಗಳು',
      painDescriptionHeader: 'ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)',
      painPlaceholder: 'ನೋವಿನ ಬಗ್ಗೆ ಬರೆಯಿರಿ...',
      submitBtn: 'ಸಲ್ಲಿಸಿ +20 XP',
      alertTitleHigh: 'ಹೆಚ್ಚಿನ ಎಚ್ಚರಿಕೆ',
      alertMsgHigh: 'ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಭೇಟಿ ಮಾಡಿ.',
      alertTitleMedium: 'ಮಧ್ಯಮ ಎಚ್ಚರಿಕೆ',
      alertMsgMedium: 'ವೈದ್ಯರಿಂದ ಸಲಹೆ ಪಡೆಯಿರಿ.',
      alertTitleStable: 'ಸ್ಥಿರ',
      alertMsgStable: 'ಲಕ್ಷಣಗಳು ಸ್ಥಿರವಾಗಿವೆ.',
      symptomNames: {
        fever: 'ಜ್ವರ',
        swelling: 'ಊತ',
        vomiting: 'ವಾಂತಿ',
        redness: 'ಕೆಂಪಾಗುವುದು',
        bleeding: 'ರಕ್ತಸ್ರಾವ',
        urination: 'ಮೂತ್ರ ವಿಸರ್ಜನೆ ತೊಂದರೆ',
      },
      noSymptomSelected: 'ಯಾವ ಲಕ್ಷಣವೂ ಇಲ್ಲ',
      reportTitle: 'ಲಕ್ಷಣಗಳ ವರದಿ',
      saveError: 'ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ. ಮತ್ತೆ ಯತ್ನಿಸಿ.',
      viewHistory: 'ದಿನಚರಿ ನೋಡಿ',
    },
    profile: {
      pageTitle: 'ಪ್ರೊಫೈಲ್',
      saveDetails: 'ವಿವರ ಉಳಿಸಿ',
      editProfile: 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
      fullNameLabel: 'ಪೂರ್ಣ ಹೆಸರು',
      fullNamePlaceholder: 'ಹೆಸರು ನಮೂದಿಸಿ',
      phoneLabel: 'ಫೋನ್ ಸಂಖ್ಯೆ',
      phonePlaceholder: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ',
      addressLabel: 'ವಿಳಾಸ',
      addressPlaceholder: 'ಮನೆಯ ವಿಳಾಸ',
      emergencyLabel: 'ತುರ್ತು ಸಂಪರ್ಕ',
      emergencyPlaceholder: 'ತುರ್ತು ಸಂಖ್ಯೆ',
      surgicalPlan: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಯ ಯೋಜನೆ',
      nameRequired: 'ಹೆಸರು ಅಗತ್ಯ',
      nameRequiredDesc: 'ಹೆಸರು ನಮೂದಿಸಿ.',
      invalidDate: 'ಅಮಾನ್ಯ ದಿನಾಂಕ',
      invalidDateDesc: 'YYYY-MM-DD ಬಳಸಿ.',
      saved: 'ಉಳಿಸಲಾಗಿದೆ',
      savedDesc: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ.',
      saveFailed: 'ಉಳಿಸಲು ವಿಫಲ',
      saveFailedDesc: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      closePicker: 'ಮುಚ್ಚಿ',
      genderLabel: 'ಲಿಂಗ',
      herniaTypeLabel: 'ಹರ್ನಿಯಾ ವಿಧ',
      surgeryStatusLabel: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ಸ್ಥಿತಿ',
      surgeryTypeLabel: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ವಿಧ',
      surgeryDateLabel: 'ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ದಿನಾಂಕ',
      surgeryDatePlaceholder: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
      logout: 'ಲಾಗ್ ಔಟ್',
      loggingOut: 'ಮುಚ್ಚಲಾಗುತ್ತಿದೆ...',
      defaultName: 'ನಿಮ್ಮ ಹೆಸರು',
      genders: {
        male: 'ಪುರುಷ',
        female: 'ಮಹಿಳೆ',
        other: 'ಇತರ',
      },
      hernias: {
        inguinal: 'ಇಂಗ್ವಿನಲ್',
        femoral: 'ಫೆಮೋರಲ್',
        umbilical: 'ಅಂಬಿಲಿಕಲ್',
        incisional: 'ಇನ್ಸಿಶನಲ್',
      },
      status: {
        notDone: 'ಮಾಡಿಲ್ಲ',
        scheduled: 'ನಿಗದಿಯಾಗಿದೆ',
        completed: 'ಪೂರ್ಣ',
      },
      types: {
        open: 'ಓಪನ್',
        laparoscopic: 'ಲ್ಯಾಪರೊಸ್ಕೋಪಿಕ್',
      },
    },
  },
  hi: {
    common: {
      cancel: 'रद्द',
      close: 'बंद',
      save: 'सहेजें',
      pending: 'लंबित',
      connected: 'जुड़े',
      connect: 'जुड़ें',
      confirm: 'पुष्टि',
    },
    dashboard: {
      hello: 'नमस्कार, {{name}}',
      helloThere: 'नमस्कार',
      countdownLabel: 'काउंटडाउन',
      totalXp: 'कुल XP',
      badges: 'बैज',
      badgesEarned: 'अर्जित बैज',
      todaysTasks: 'आज के कार्य',
      allCompletedTitle: 'सब पूरा!',
      allCompletedSubtitle: 'दैनिक कार्य पूरे हुए!',
      completedBtn: 'पूर्ण',
      tasksCompletedToday: 'आज पूर्ण हुए',
      noTasksCompleted: 'कोई नहीं हुआ।',
      dailyStreak: 'स्ट्रीक',
      streakDays: '{{count}} दिन',
      phases: {
        preop: 'सर्जरी-पूर्व',
        postop: 'सर्जरी-बाद',
        recovery: 'रिकवरी',
        setup: 'सेटअप',
      },
      tasks: {
        medication_logged: 'दवाएं लिखें',
        medication_logged_desc: 'दैनिक दवाएं चिह्नित करें',
        daily_logging: 'दैनिक लॉगिन',
        daily_logging_desc: 'दैनिक ऐप खोलें',
        wound_photo: 'फोटो डालें',
        wound_photo_desc: 'घाव की फोटो अपलोड करें',
        symptoms_logging: 'लक्षण लिखें',
        symptoms_logging_desc: 'दर्द व लक्षण दर्ज करें',
        autoCompleteHint: 'दर्ज करने पर पूर्ण',
      }
    },
    activity: {
      pageTitle: 'देखभाल योजना',
      canDoTitle: 'अनुशंसित',
      notToDoTitle: 'बचें',
      canDoSlides: {
        slide1: {
          title: 'फाइबर आहार',
          subtitle: 'फल, सब्जी, साबुत अनाज खाएं',
        },
        slide2: {
          title: 'पर्याप्त पानी',
          subtitle: 'दिनभर खूब पानी पीते रहें',
        },
        slide3: {
          title: 'हल्की सैर',
          subtitle: 'धीमी सैर से सक्रिय रहें',
        },
        slide4: {
          title: 'बिस्तर आराम',
          subtitle: 'पर्याप्त आराम सुनिश्चित करें',
        },
        slide5: {
          title: 'हल्के काम',
          subtitle: 'बिना वजन उठाए छोटे काम करें',
        },
      },
      notToDoSlides: {
        slide1: {
          title: 'जंक फूड',
          subtitle: 'तले व भारी भोजन से बचें',
        },
        slide2: {
          title: 'शराब',
          subtitle: 'ठीक होने तक शराब से बचें',
        },
        slide3: {
          title: 'दौड़ना',
          subtitle: 'दौड़ने या भारी व्यायाम से बचें',
        },
        slide4: {
          title: 'वजन उठाना',
          subtitle: '५ पाउंड से अधिक न उठाएं',
        },
        slide5: {
          title: 'झुकना',
          subtitle: 'कमर के बजाय घुटने मोड़ें',
        },
      },
    },
    diary: {
      pageTitle: 'डायरी',
      empty: 'कोई प्रविष्टि नहीं। नीचे जोड़ें।',
      loadMore: 'और लोड करें',
      addTodayEntry: '+ लॉग जोड़ें',
      placeholder: 'आज कैसा महसूस कर रहे हैं...',
      saveXp: 'सहेजें +15 XP',
      selectMood: 'मनोदशा',
      selectMoodAlertTitle: 'मनोदशा',
      selectMoodAlertDesc: 'कृपया मनोदशा चुनें।',
      tooShortAlertTitle: 'बहुत छोटा',
      tooShortAlertDesc: 'कम से कम 10 अक्षर लिखें।',
      entryAddedAlertTitle: 'सहेज लिया ✅',
      entryAddedAlertDesc: '+15 XP प्राप्त हुए!',
      todayHeader: 'आज',
      olderEntriesHeader: 'पुराने लॉग',
      noEntriesToday: 'आज कोई लॉग नहीं लिखा।',
      deleteTitle: 'लॉग हटाएं',
      deleteConfirm: 'क्या आप वाकई इस लॉग को हटाना चाहते हैं?',
      deleteSuccess: 'लॉग सफलतापूर्वक हटा दिया गया।',
      deleteError: 'लॉग नहीं हटा सके। फिर प्रयास करें।',
    },
    experts: {
      pageTitle: 'डॉक्टर खोजें',
      careTeamTitle: 'देखभाल टीम',
      emptyDoctors: 'कोई डॉक्टर नहीं मिले।',
      searchPlaceholder: 'नाम या फोन से खोजें...',
      hospitalLocation: 'अस्पताल का स्थान',
      confirmBooking: 'पुष्टि करें',
      bookAppointment: 'अपॉइंटमेंट बुक करें',
      specialistSubtitle: 'हर्निया विशेषज्ञ',
      rating: 'रेटिंग',
      reviews: 'समीक्षा',
      consultationFee: 'शुल्क',
      experience: 'अनुभव',
      years: 'वर्ष',
      location: 'स्थान',
      aboutDoctor: 'डॉक्टर के बारे में',
      removeConnection: 'संपर्क हटाएं',
      removeConnectionDesc: 'संपर्क हटाना चाहते हैं?',
      removePendingDesc: 'अनुरोध रद्द करना चाहते हैं?',
      appointmentBooked: 'बुक हो गया! ✅',
      appointmentBookedDesc: 'अपॉइंटमेंट निर्धारित है।',
      noDoctorsFound: 'डॉक्टर नहीं मिले',
      noDoctorsAvailable: 'डॉक्टर उपलब्ध नहीं',
      noDoctorsFoundDesc: 'कोई डॉक्टर नहीं मिला।',
      noDoctorsAvailableDesc: 'नए विशेषज्ञ उपलब्ध नहीं हैं।',
      viewProfile: 'प्रोफ़ाइल देखें →',
      loadingDoctors: 'लोड हो रहा है...',
      connectWithSpecialist: 'विशेषज्ञ से जुड़ें',
      connectWithSpecialistDesc: 'लॉग और फोटो साझा करें।',
      connectWithDoctorBtn: 'जुड़ें',
      requestsPending: 'लंबित अनुरोध',
      requestsPendingDesc: 'डॉक्टर की मंजूरी का इंतजार है।',
      pendingRequestsLabel: 'लंबित ({{count}})',
      profileBtn: 'प्रोफ़ाइल',
      requestSentTitle: 'भेज दिया 📩',
      requestSentDesc: 'अनुरोध सफलतापूर्वक भेजा गया।',
      errorTitle: 'त्रुटि',
      sendRequestError: 'अनुरोध नहीं भेजा जा सका।',
    },
    reports: {
      pageTitle: 'घाव का स्वास्थ्य',
      uploadTitle: 'फोटो डालें',
      uploadDesc: 'घाव ठीक होने की निगरानी',
      sectionHeader: 'घाव के चित्र',
      deleteTitle: 'फोटो हटाएं',
      deleteConfirm: 'क्या फोटो हटाना चाहते हैं?',
      successUpload: 'अपलोड पूर्ण ✅',
      successUploadDesc: 'फोटो अपलोड! +30 XP.',
      failUpload: 'अपलोड विफल',
      failUploadDesc: 'अपलोड नहीं हुआ। फिर प्रयास करें।',
      careTipsHeader: 'देखभाल के टिप्स',
      warningSignsHeader: 'चेतावनी के संकेत',
      careTips: {
        clean: 'साफ और सूखा रखें',
        cleanSub: 'कटने वाले हिस्से को बचाएं',
        clothes: 'ढीले कपड़े पहनें',
        clothesSub: 'तंग कपड़ों से बचें',
        dressing: 'रोज पट्टी बदलें',
        dressingSub: 'स्वच्छता बनाए रखें',
        scratch: 'खुजली न करें',
        scratchSub: 'घाव की जलन को रोकें',
        meds: 'समय पर दवा लें',
        medsSub: 'दर्द निवारण व सुधार',
        call: 'परेशानी पर डॉक्टर से पूछें',
        callSub: 'जल्द से जल्द सहायता लें',
      },
      warningSigns: {
        redness: 'लालिमा',
        rednessSub: 'फैलती लालिमा पर नजर रखें',
        swelling: 'सूजन',
        swellingSub: 'असामान्य सूजन की जांच करें',
        pus: 'पीप आना',
        pusSub: 'पीले रिसाव की रिपोर्ट करें',
        bleeding: 'रक्तस्राल',
        bleedingSub: 'सक्रिय रक्तस्राव पर नजर रखें',
      },
    },
    monitor: {
      pageTitle: 'लक्षण रिपोर्ट',
      loggedDetails: 'दर्ज विवरण',
      severityRating: 'तीव्रता:',
      highSeverity: 'उच्च',
      mediumSeverity: 'मध्यम',
      mildSeverity: 'कम',
      loggedSymptoms: 'लक्षण:',
      notes: 'टिप्पणी:',
      done: 'पूर्ण',
      logTitle: 'लक्षण दर्ज करें',
      painHeader: 'दर्द का स्तर (1-10)',
      symptomsHeader: 'लक्षण',
      painDescriptionHeader: 'टिप्पणी (वैकल्पिक)',
      painPlaceholder: 'दर्द का संक्षेप में वर्णन करें...',
      submitBtn: 'सहेजें +20 XP',
      alertTitleHigh: 'उच्च अलर्ट',
      alertMsgHigh: 'कृपया तुरंत डॉक्टर से मिलें।',
      alertTitleMedium: 'मध्यम अलर्ट',
      alertMsgMedium: 'सलाह के लिए डॉक्टर से पूछें।',
      alertTitleStable: 'स्थिर',
      alertMsgStable: 'लक्षण स्थिर हैं।',
      symptomNames: {
        fever: 'बुखार',
        swelling: 'सूजन',
        vomiting: 'उल्टी',
        redness: 'लालिमा',
        bleeding: 'रक्तस्राव',
        urination: 'पेशाब में कठिनाई',
      },
      noSymptomSelected: 'कोई लक्षण नहीं चुना',
      reportTitle: 'लक्षण रिपोर्ट',
      saveError: 'सहेज नहीं सके। फिर प्रयास करें।',
      viewHistory: 'इतिहास देखें',
    },
    profile: {
      pageTitle: 'प्रोफ़ाइल',
      saveDetails: 'विवरण सहेजें',
      editProfile: 'प्रोफ़ाइल बदलें',
      fullNameLabel: 'पूरा नाम',
      fullNamePlaceholder: 'नाम दर्ज करें',
      phoneLabel: 'फ़ोन नंबर',
      phonePlaceholder: 'आपका फ़ोन नंबर',
      addressLabel: 'पता',
      addressPlaceholder: 'घर का पता',
      emergencyLabel: 'आपातकालीन संपर्क',
      emergencyPlaceholder: 'आपातकालीन नंबर',
      surgicalPlan: 'सर्जिकल योजना',
      nameRequired: 'नाम आवश्यक',
      nameRequiredDesc: 'अपना नाम दर्ज करें।',
      invalidDate: 'अमान्य तिथि',
      invalidDateDesc: 'YYYY-MM-DD प्रारूप का उपयोग करें।',
      saved: 'सहेज लिया गया',
      savedDesc: 'प्रोफ़ाइल अपडेट हो गई।',
      saveFailed: 'सहेजना विफल',
      saveFailedDesc: 'पुनः प्रयास करें।',
      closePicker: 'बंद करें',
      genderLabel: 'लिंग',
      herniaTypeLabel: 'हर्निया का प्रकार',
      surgeryStatusLabel: 'सर्जरी स्थिति',
      surgeryTypeLabel: 'सर्जरी प्रकार',
      surgeryDateLabel: 'सर्जरी तिथि',
      surgeryDatePlaceholder: 'सर्जरी तिथि चुनें',
      logout: 'लॉग आउट',
      loggingOut: 'लॉग आउट हो रहा है...',
      defaultName: 'आपका नाम',
      genders: {
        male: 'पुरुष',
        female: 'महिला',
        other: 'अन्य',
      },
      hernias: {
        inguinal: 'इंगुइनल',
        femoral: 'फेमोरल',
        umbilical: 'अम्बिलिकल',
        incisional: 'इन्सिशनल',
      },
      status: {
        notDone: 'नहीं हुई',
        scheduled: 'निर्धारित',
        completed: 'पूरी हुई',
      },
      types: {
        open: 'ओपन',
        laparoscopic: 'लैप्रोस्कोपिक',
      },
    },
  }
};

export interface LanguageState {
  language: LanguageCode;
}

export interface LanguageActions {
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

export const useLanguageStore = create<LanguageState & LanguageActions>()(
  persist(
    (set, get) => ({
      language: 'en',

      setLanguage: (() => {
        let timer: ReturnType<typeof setTimeout> | null = null;
        return (lang: LanguageCode) => {
          if (timer) clearTimeout(timer);
          timer = setTimeout(() => {
            set({ language: lang });
            timer = null;
          }, 200);
        };
      })(),

      t: (key, replacements) => {
        const lang = get().language;
        const dict = translations[lang] || translations.en;
        
        // Resolve nested keys using dot notation
        const parts = key.split('.');
        let current: any = dict;
        for (const part of parts) {
          if (current && current[part] !== undefined) {
            current = current[part];
          } else {
            // Fallback to English dictionary
            let engFallback: any = translations.en;
            for (const p of parts) {
              if (engFallback && engFallback[p] !== undefined) {
                engFallback = engFallback[p];
              } else {
                return key;
              }
            }
            current = engFallback;
            break;
          }
        }

        if (typeof current !== 'string') {
          return key;
        }

        // Apply replacements if provided
        let text = current;
        if (replacements) {
          Object.entries(replacements).forEach(([k, v]) => {
            text = text.replace(new RegExp(`{{${k}}}`, 'g'), String(v));
          });
        }

        return text;
      },
    }),
    {
      name: 'herniacare-language',
      storage: createJSONStorage(() => AsyncStorage),
    }
  )
);
